build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

comments:
  active: true

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  ReturnCount:
    active: false

complexity:
  LargeClass:
    active: false
  LongMethod:
    active: true
    threshold: 140
  LongParameterList:
    active: true
    functionThreshold: 15
    constructorThreshold: 25
  TooManyFunctions:
    active: false

naming:
  VariableNaming:
    active: false
  FunctionNaming:
    active: false